### ISSUE TITLE
The valid /set command meta.match.wb is not documented at the FAQ

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#967]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome OS Version 102.0.5005.75 (Official Build) (64-bit)

### Browser and version

Chrome OS Version 102.0.5005.75 (Official Build) (64-bit)

### Describe the bug/issue

PTAL at https://tetrio.team2xh.net/faq#commands. `meta.match.wb` is not documented as a valid command, but when I try (for example) `meta.match.wb=3` in a private room, it works.

### Reproducing

Notice that there's not example usage of the command `meta.match.wb` in the FAQ, even though it's a valid command.

### Expected behavior

An example of the command `meta.match.wb` is documented in the FAQ.

**Comment by ZaptorZap** [comment]
Sorry, but [Tenchi's TETR.IO Statistics](https://tetrio.team2xh.net/faq#commands) isn't under the scope of this issue repository, since it's an unofficial fan project. The pinned message in #tetrio on our [Discord server](https://l.tetr.io/discord) **is up to date,** if you need that. @Tenchi2xh should be notified of the issue, to be clear.
